services:
  fds-ui:
    build:
      context: .
      # only needed if not named Dockerfile
      # dockerfile: Dockerfile
      # can target different stages of the Dockerfile
      # target: dev
    ports:
      - 4200:4200
    container_name: ui
    volumes:
      - ./:/opt/fds
      - /opt/fds/node_modules
