export const dummyOptions = [
  {
    cb: 'Catalog ID',
    checked: true,
    disabled: false,
    value: 30182,
  },
  {
    cb: 'Eccentricity',
    checked: true,
    disabled: false,
    value: 92.39401,
  },
  {
    cb: 'Mass',
    checked: true,
    disabled: false,
    value: 43.28404,
  },
  {
    cb: 'Raan',
    checked: false,
    disabled: true,
    unit: 'deg',
    value: 206.6145,
    options: [
      { value: 'deg', label: 'Degree' },
      { value: 'rad', label: 'Radian' },
      { value: 'rev', label: 'Revolution' },
    ],
  },
  {
    cb: 'Mean Motion',
    checked: false,
    disabled: true,
    unit: 'deg',
    value: 1.790294538,
    options: [
      { value: 'deg', label: 'Degree' },
      { value: 'rad', label: 'Radian' },
      { value: 'rev', label: 'Revolution' },
    ],
  },
  {
    cb: 'Perigee',
    checked: true,
    disabled: false,
    unit: 'km',
    value: 363396432,
    options: [
      { value: 'm', label: 'Meters' },
      { value: 'km', label: 'Kilometers' },
      { value: 'mi', label: 'Miles' },
    ],
  },

  {
    cb: 'True Longitude',
    checked: false,
    disabled: true,
    unit: 'deg',
    value: 0.05,
    options: [
      { value: 'deg', label: 'Degree' },
      { value: 'rad', label: 'Radian' },
      { value: 'rev', label: 'Revolution' },
    ],
  },
  {
    cb: 'True Anomaly',
    checked: false,
    disabled: true,
    unit: 'deg',
    value: 0.1,
    options: [
      { value: 'deg', label: 'Degree' },
      { value: 'rad', label: 'Radian' },
      { value: 'rev', label: 'Revolution' },
    ],
  },
  {
    cb: 'Mean Anomaly',
    checked: false,
    disabled: true,
    unit: 'deg',
    value: 0.90723429381761343,
    options: [
      { value: 'deg', label: 'Degree' },
      { value: 'rad', label: 'Radian' },
      { value: 'rev', label: 'Revolution' },
    ],
  },
  {
    cb: 'Inclination',
    checked: true,
    disabled: false,
    unit: 'deg',
    value: 23.4362,
    options: [
      { value: 'deg', label: 'Degree' },
      { value: 'rad', label: 'Radian' },
      { value: 'rev', label: 'Revolution' },
    ],
  },
  {
    cb: 'Semi-Major Axis',
    checked: true,
    disabled: false,
    unit: 'km',
    value: 63714327,
    options: [
      { value: 'm', label: 'Meters' },
      { value: 'km', label: 'Kilometers' },
      { value: 'm', label: 'Miles' },
    ],
  },
];
